# Generated by Django 3.0.5 on 2020-04-10 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('losings', models.IntegerField(blank=True, default=0)),
                ('rating', models.FloatField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField(blank=True, max_length=50, unique=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('firstPlayer_choice', models.TextField(blank=True, choices=[('stone', 'stone'), ('scissors', 'scissors'), ('paper', 'paper'), ('lizard', 'lizard'), ('spock', 'spock')])),
                ('secondPlayer_choice', models.TextField(blank=True, choices=[('stone', 'stone'), ('scissors', 'scissors'), ('paper', 'paper'), ('lizard', 'lizard'), ('spock', 'spock')])),
                ('status', models.TextField(choices=[('waiting', 'waiting'), ('completed', 'completed'), ('playing', 'playing')], default='waiting')),
                ('firstPlayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='firstPlayer', to=settings.AUTH_USER_MODEL)),
                ('secondPlayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondPlayer', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
