# Generated by Django 3.0.5 on 2020-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='firstPlayer_choice',
            field=models.TextField(blank=True, choices=[('stone', 'stone'), ('paper', 'paper'), ('lizard', 'lizard')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondPlayer_choice',
            field=models.TextField(blank=True, choices=[('stone', 'stone'), ('paper', 'paper'), ('lizard', 'lizard')]),
        ),
    ]
